name: Pipeline

on: [push]

jobs:
  Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: yarn
    - run: yarn global add @quasar/cli
    - run: quasar mode add capacitor
    - run: quasar build -m capacitor -T android
    - run: /usr/local/lib/android/sdk/build-tools/31.0.0/apksigner sign --ks=./resource/key.jks --ks-pass=pass:123456 --ks-key-alias=key0 --key-pass=pass:123456 --out=./dist/capacitor/android/apk/release/app-release-signed.apk ./dist/capacitor/android/apk/release/app-release-unsigned.apk
    - run: /usr/local/lib/android/sdk/build-tools/31.0.0/apksigner verify -v ./dist/capacitor/android/apk/release/app-release-signed.apk
    - uses: actions/upload-artifact@v3
      with:
        name: dist-capacitor-android
        path: ./dist/capacitor/android
